version: '3.8'

services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass password --port 6379
    container_name: redis6379
    hostname: redis6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379